# Generated by Django 6.1 on 2026-09-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_booking_district_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_notes',
            field=models.TextField(blank=True, default='', verbose_name='طلب وملاحظات العميل بالتفصيل'),
        ),
    ]
