# Generated by Django 6.1 on 2026-09-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_booking_customer_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'حجز صيانة', 'verbose_name_plural': 'حجوزات الصيانة'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'تم تأكيد الحجز 🟢'), ('on_the_way', 'سيارة الصيانة في الطريق 🚚'), ('in_progress', 'جاري الصيانة بموقعك ⚙️'), ('completed', 'اكتملت الصيانة بنجاح ✅'), ('cancelled', 'تم الإلغاء ❌')], db_index=True, default='confirmed', max_length=20, verbose_name='حالة أمر العمل'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='booking_app_booking_04b71c_idx'),
        ),
    ]
