# Generated by Django 6.1 on 2026-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_booking_options_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='EGS Garage - ورشة صيانة متنقلة', max_length=150, verbose_name='اسم المركز / الورشة')),
                ('hotline_number', models.CharField(default='01019900990', max_length=30, verbose_name='رقم التليفون المكتوب في اليافطه (الهيدر والمجسم والفرع)')),
                ('short_hotline', models.CharField(default='19900', max_length=20, verbose_name='الرقم المختصر (مثل 19900)')),
                ('whatsapp_number', models.CharField(default='201019900990', max_length=30, verbose_name='رقم الواتساب للاستفسارات')),
                ('instapay_number', models.CharField(default='01019900990', max_length=30, verbose_name='رقم انستاباي للدفع الرقمي')),
                ('center_address', models.CharField(default='مركز EGS الرئيسي - المنطقة الصناعية، مدينة 6 أكتوبر', max_length=250, verbose_name='عنوان الفرع الرئيسي')),
            ],
            options={
                'verbose_name': 'إعدادات المنصة ورقم اليافطة',
                'verbose_name_plural': 'إعدادات المنصة ورقم اليافطة',
            },
        ),
    ]
